# Site Settings
title: Nick Adams, Designer
email: hi@nick-adams.com
description: The site and portfolio of Nick Adams, a Designer based in Rochester, NY.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nick-adams.com" # the base hostname & protocol for your site

twitter_username: nickadamssays
github_username:  nick-adams

# Collection Settings
collections:
  case-studies:
    output: true
    permalink: /case-studies/:path/
    
# Default FrontMatter for Posts
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: posts
      permalink: /notes/:year/:title/ 
      nav_selected: notes
      header_nav_color: is--on-light

# Build Settings
destination: ./www

permalink: pretty

sass:
  sass_dir: ./assets/css
  style: :expanded
