# Site settings
title: >
    Nick Adams, Designer
email: hi@nick-adams.com
description: >
    The site and portfolio of Nick Adams, a Designer based in Rochester, NY.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nick-adams.com" # the base hostname & protocol for your site
twitter_username: nickadamssays
github_username:  nick-adams

# Collections
collections:
- work
    output: true
    permalink: /work/:path/

# Build settings
sass:
    sass_dir: ./assets/css
    style: :expanded
markdown: kramdown
permalink: /notes/:year/:title.html #for blog posts only